[project]
name = "socialautomation"
version = "1.0.0"
description = "The social media automation app built in the Flask tutorial."
dependencies = [
    "flask",
    "instagrapi"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"